### ISSUE TITLE
[ Beta 5] Mkdir executable format error

### ISSUE THREAD

**Issue by atirutw** [oc-ulos/ulos-2#5]
![image](https://github.com/user-attachments/assets/ea59b081-2785-4f92-bd61-c8fe231c47ad)

**Comment by Ocawesome101** [comment]
ULOS 2 needs lua 5.3.  this looks like you're running it on 5.2.

**Comment by Ocawesome101** [comment]
on second thought i'm not sure how it would have even booted though.  lemme check for a merge conflict in that file.

**Comment by Ocawesome101** [comment]
alright this looks like a merge artifact.  i'll rebuild the packages.

**Comment by Ocawesome101** [comment]
fixed.  update (or reinstall) and try again.

**Comment by atirutw** [comment]
Is `uptu`/`upt update` not fetching the fix an issue on the ULOS side? I had to run `upt i coreutils` instead.

**Comment by Ocawesome101** [comment]
yeah i didn't bump the version.
